plugins {
    id 'java'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = 11
}

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

repositories {
    mavenCentral()
}

dependencies {
    // Selenide
    testImplementation 'com.codeborne:selenide:6.19.1'

    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'

    // JavaFaker
    testImplementation 'com.github.javafaker:javafaker:1.0.2'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.26'
    testCompileOnly 'org.projectlombok:lombok:1.18.26'
    annotationProcessor 'org.projectlombok:lombok:1.18.26'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.26'

    // JUnit 5 Platform
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    systemProperty 'selenide.headless', System.getProperty('selenide.headless')
    systemProperty 'chromeoptions.prefs', System.getProperty('chromeoptions.prefs', "profile.password_manager_leak_detection=false")
}