plugins {
    id 'java'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Selenide
    testImplementation 'com.codeborne:selenide:6.12.4'

    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'

    // JavaFaker
    testImplementation 'com.github.javafaker:javafaker:1.0.2'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.26'
    testCompileOnly 'org.projectlombok:lombok:1.18.26'
    annotationProcessor 'org.projectlombok:lombok:1.18.26'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.26'

    // JUnit 5 Platform
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    systemProperty 'selenide.headless', System.getProperty('selenide.headless')
}